### ISSUE TITLE
Add Stream Deck Neo support

### ISSUE THREAD

**Issue by CharlesCanlom** [StreamController/StreamController#240] opened 2024-09-21 19:35 UTC
**Describe the feature idea**
I twould be easier if the Stream Deck Neo is added, since it's the only Stream Deck i have.

**Additional context**

**Comment by Core447** [comment] 2024-09-22 10:58
Support for the normal buttons is already added and tested on the `sd-neo` branch. Will close this because it's a duplicate of #141, head over to it if you want to read more about the current state of the neo support.

**Closed as completed by Core447** 2024-09-22 10:58 UTC
Labels: enhancement
